In [1]:
# NumPy and Pandas Assignment
# Complete the following tasks by filling in the code where indicated.
# Ensure your notebook is well-documented with markdown cells explaining your code and results.

import numpy as np
import pandas as pd

# Task 1: NumPy Basics

### Array Creation
#### 1. Create an array of 10 zeros but set the fifth element to 1.


In [2]:
def create_numpy_array():
    # We use np.zeros() to create an array initialized with zeros
    # The dtype=int parameter ensures integer data type instead of default
    arr = np.zeros(10, dtype=int)
    
    # Index 4 is the fifth element (zero-based indexing)
    arr[4] = 1
    
    return arr

In [3]:
my_array = create_numpy_array()
create_numpy_array()

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

### 2. Create a 4x4 matrix with values ranging from 0 to 15.

In [4]:
def create_matrix():
    # 'np.arange(16)' creates sequential numbers from 0 to 15
    # 'reshape(4, 4)' transforms the 1D array into a 4x4 matrix
    # The result is a square matrix with values increasing row by row
    return np.arange(16).reshape(4,4)

In [5]:
create_matrix()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Array Operations

#### 3. Create two NumPy arrays: Perform element-wise addition, subtraction, multiplication, and division.
#### arr1: array([[41, 30, 10], [ 6, 35, 23], [23,  9, 10]])
#### arr2: array([[4, 29,  2], [5, 13,  3], [24, 16,  7]])

In [6]:
def array_operations():
    arr1 = np.array([[41, 30, 10], [ 6, 35, 23], [23, 9, 10]])
    arr2 = np.array([[4, 29, 2], [5, 13, 3], [24, 16, 7]])
    # Element-wise operations are performed automatically
    # No explicit loops needed
    # Operations maintain array dimensions
    addition = arr1 + arr2
    subtraction = arr1 - arr2
    multiplication = arr1 * arr2
    division = arr1 / arr2
    print(f"Addition:\n {addition}")
    print(f"Subtraction:\n {subtraction}")
    print(f"Multiplication:\n {multiplication}")
    print(f"Division:\n {division}")

In [7]:
array_operations()

Addition:
 [[45 59 12]
 [11 48 26]
 [47 25 17]]
Subtraction:
 [[37  1  8]
 [ 1 22 20]
 [-1 -7  3]]
Multiplication:
 [[164 870  20]
 [ 30 455  69]
 [552 144  70]]
Division:
 [[10.25        1.03448276  5.        ]
 [ 1.2         2.69230769  7.66666667]
 [ 0.95833333  0.5625      1.42857143]]


### Array Slicing
#### 4. Given the array: 
#### arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
#### Extract elements from index 2 to 6.

In [8]:
def array_slicing():
    # Create array with values from 10 to 100 in steps of 10
    arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
    # Slice array from index 2 (inclusive) to 7 (exclusive)
    # This gets elements at indices 2, 3, 4, 5, and 6
    return arr[2:7]

In [9]:
array_slicing()

array([30, 40, 50, 60, 70])

### Using NumPy Methods
#### 5. Convert the array below to a 3×3 NumPy array.
#### array([[15, 18, 20], [15, 30, 8], [25, 30, 60]])
#### Find the mean, sum, and maximum value.

In [10]:
def numpy_methods():
    arr = np.array([[15, 18, 20], 
                    [15, 30, 8], 
                    [25, 30, 60]])
    
    # Calculate statistics
    mean_value = round(arr.mean(), 2)  # Round mean to 2 decimal places
    sum_value = arr.sum()
    max_value = arr.max()
    
    # Display results
    print(f"Mean: {mean_value}")
    print(f"Sum: {sum_value}")
    print(f"Maximum: {max_value}")

In [11]:
numpy_methods()

Mean: 24.56
Sum: 221
Maximum: 60


# Task 2: Pandas Basics

### Creating a Pandas Series
#### 1. Create a Pandas Series from the list [10, 20, 30, 40, 50] with index labels 'a', 'b', 'c', 'd', 'e'.

In [12]:
def create_series():
    # Create a list with values [10, 20, 30, 40, 50]
    list1 = [10, 20, 30, 40, 50]
    # Custom index labels ['a', 'b', 'c', 'd', 'e']
    labels = ['a', 'b', 'c', 'd', 'e']

    # Create series from list assigning custom index labels
    return pd.Series(list1, index = labels)

In [13]:
create_series()

a    10
b    20
c    30
d    40
e    50
dtype: int64

### Reading a CSV File
#### 2. Read a CSV file named "data.csv" into a Pandas DataFrame. The CSV file has the following columns: "Name", "Age", "Salary".

In [14]:
def read_a_csv():
    # Read a csv file
    file = pd.read_csv('data/data.csv')

    # Create a data-frame from the csv file content
    df = pd.DataFrame(file)
    return df

In [15]:
df = read_a_csv()
df

Name  Age  Salary
0     Alice   29   73193
1       Bob   53   85398
2   Charlie   36   47162
3     David   22   65853
4       Eve   24   36168
5     Frank   58   69657
6     Grace   41   85202
7    Hannah   38   62421
8     Isaac   50   74641
9      Jack   47   38963
10    Karen   34   32136
11      Leo   49   41874
12     Mona   56   34070
13     Nina   49   91734
14    Oscar   30   89539
15     Paul   23   78720
16    Quinn   31   54424
17   Rachel   54   59900
18    Steve   36   32163
19     Tina   56   52054

### Slicing a DataFrame
#### 3. From the DataFrame created in Exercise 2, select only the first three rows.

In [16]:
def slice_dataframe(df):
    # Using iloc to select rows by integer position
    # :3 means from start (0) up to but not including index 3
    # This will select rows 0, 1, and 2 (first three rows)
    return df.iloc[:3]

In [17]:
slice_dataframe(df)

Name  Age  Salary
0    Alice   29   73193
1      Bob   53   85398
2  Charlie   36   47162

### Manipulating a DataFrame - Adding a Column
#### 4. Add a new column named "Tax" to the DataFrame from Exercise 2. The tax should be calculated as 10% of the "Salary" column.

In [18]:
def add_tax_column(df):
    # Create new column 'Tax' with calculated tax value as 10% of salary
    df["Tax"] = df["Salary"] * 0.1
    return df

In [19]:
add_tax_column(df)

Name  Age  Salary     Tax
0     Alice   29   73193  7319.3
1       Bob   53   85398  8539.8
2   Charlie   36   47162  4716.2
3     David   22   65853  6585.3
4       Eve   24   36168  3616.8
5     Frank   58   69657  6965.7
6     Grace   41   85202  8520.2
7    Hannah   38   62421  6242.1
8     Isaac   50   74641  7464.1
9      Jack   47   38963  3896.3
10    Karen   34   32136  3213.6
11      Leo   49   41874  4187.4
12     Mona   56   34070  3407.0
13     Nina   49   91734  9173.4
14    Oscar   30   89539  8953.9
15     Paul   23   78720  7872.0
16    Quinn   31   54424  5442.4
17   Rachel   54   59900  5990.0
18    Steve   36   32163  3216.3
19     Tina   56   52054  5205.4

#### Filter the dataframe by the column "age" whereby the age is above 36 years

In [20]:
def filter_by_age(df):
    # Apply filter using boolean indexing
    # df["Age"] > 36 creates a boolean mask
    # True for ages > 36, False for others
    return df[df["Age"] > 36]

In [21]:
filter_by_age(df)

Name  Age  Salary     Tax
1      Bob   53   85398  8539.8
5    Frank   58   69657  6965.7
6    Grace   41   85202  8520.2
7   Hannah   38   62421  6242.1
8    Isaac   50   74641  7464.1
9     Jack   47   38963  3896.3
11     Leo   49   41874  4187.4
12    Mona   56   34070  3407.0
13    Nina   49   91734  9173.4
17  Rachel   54   59900  5990.0
19    Tina   56   52054  5205.4

# Task 3: Data Analysis with Pandas

### Aggregation - Compute Total and Mean Sales
#### 1. Given a dataset of sales transactions, compute the total and mean sales per region.

In [22]:
# Sample Data
sales_data = pd.DataFrame({
    "Region": ["North", "South", "North", "West", "South", "West"],
    "Sales": [1000, 1500, 1200, 1800, 1300, 1700]
})
sales_data.head()

Region  Sales
0  North   1000
1  South   1500
2  North   1200
3   West   1800
4  South   1300

In [23]:
def analyze_sales(sales_data):
    # Group data by Region and calculate analytics
    # agg(['sum', 'mean']) computes both sum and mean for each region
    analytics = sales_data.groupby('Region')['Sales'].agg(['sum', 'mean'])
    return analytics

In [24]:
analyze_sales(sales_data)

sum    mean
Region              
North   2200  1100.0
South   2800  1400.0
West    3500  1750.0

### Merging - Combine Customer and Order Data
#### 2. Merge customers and orders data based on CustomerID.

In [25]:
customers = pd.DataFrame({
    "CustomerID": [1, 2, 3, 4],
    "CustomerName": ["Alice", "Bob", "Charlie", "David"]
})

orders = pd.DataFrame({
    "OrderID": [101, 102, 103, 104],
    "CustomerID": [1, 2, 2, 4],
    "Amount": [250, 400, 600, 150]
})

print(customers.head(2), orders.head(2))

   CustomerID CustomerName
0           1        Alice
1           2          Bob    OrderID  CustomerID  Amount
0      101           1     250
1      102           2     400


In [26]:
def merged_customer_order_data(customers, orders):
    # Perform inner merge on CustomerID
    # - Inner merge keeps only matching records from both DataFrames
    # - 'on' parameter specifies the column to merge on
    merged_df = pd.merge(customers, orders, on="CustomerID")
    return merged_df

In [27]:
merged_customer_order_data(customers, orders)

CustomerID CustomerName  OrderID  Amount
0           1        Alice      101     250
1           2          Bob      102     400
2           2          Bob      103     600
3           4        David      104     150

### Joining - Left Join Employee Data
#### 4. Perform a left join between employees and departments on DeptID.

In [28]:
employees = pd.DataFrame({
    "EmpID": [101, 102, 103, 104],
    "EmpName": ["John", "Jane", "Alice", "Bob"],
    "DeptID": [1, 2, 2, 3]
})

departments = pd.DataFrame({
    "DeptID": [1, 2],
    "DeptName": ["HR", "Finance"]
})

print(employees.head(2), departments.head(2))

   EmpID EmpName  DeptID
0    101    John       1
1    102    Jane       2    DeptID DeptName
0       1       HR
1       2  Finance


In [29]:
def join_department_employee_data(employees, departments):
    # Perform left join on DeptID
    # - Left join keeps all records from employees (left) DataFrame
    # - Matches department info where possible
    # - Fills with NaN for employees whose DeptID doesn't match any department
    joined_df = pd.merge(employees, departments, on="DeptID", how="left")
    return joined_df

In [30]:
join_department_employee_data(employees, departments)

EmpID EmpName  DeptID DeptName
0    101    John       1       HR
1    102    Jane       2  Finance
2    103   Alice       2  Finance
3    104     Bob       3      NaN

### Pivot Table - Summarize Sales Data
#### 4. Create a pivot table showing total sales for each Region and Product.

In [31]:
sales_pivot_data = pd.DataFrame({
    "Region": ["North", "North", "South", "South", "West", "West"],
    "Product": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 300, 150, 400, 250, 500]
})

sales_pivot_data.head(2)

Region Product  Sales
0  North       A    200
1  North       B    300

In [32]:
def create_sales_pivot_table(sales_pivot_data):
    # Create pivot table
    # - values='Sales': The values to aggregate
    # - index='Product': Products will be the row labels
    # - columns='Region': Regions will be the column labels
    # - aggfunc='sum': Sum the sales for each Product-Region combination
    return pd.pivot_table(
        sales_pivot_data,
        values='Sales',
        index='Region',
        columns='Product',
        aggfunc='sum'
    )

In [33]:
create_sales_pivot_table(sales_pivot_data)

Product    A    B
Region           
North    200  300
South    150  400
West     250  500